before_script:
  - chcp 65001

stages:
  - build
  - pack

build:
  stage: build
  script:
    - ".\\build.bat"
  artifacts:
    paths:
      - "WindowDebugger\\bin\\Release\\"
    expire_in: 1h

pack:
  stage: pack
  only:
   - master
  script:
    - ".\\pack.bat"
  artifacts:
    paths:
      - "WindowDebugger.netcoreapp3.1.7z"
    expire_in: 1h
