Product.LocalizedName = "Window Debugger"
App.UI.SearchWatermark = "Search"
App.UI.SettingsButton = "Settings"
App.UI.AboutButton = "Settings"
App.UI.Filter.DefaultFilter = "Visible Top-Level"
App.UI.Filter.FilterTitle = "Including these windows"
App.UI.Filter.FilterDescription = "By default, only visible top-level windows are shown in the list. Check to show more windows."
App.UI.Filter.IncludingInvisibleWindow = "Invisible Window"
App.UI.Filter.IncludingEmptyTitleWindow = "Empty Title Window"
App.UI.Filter.IncludingChildWindow = "Child Window"
App.UI.Filter.IncludingMessageOnlyWindow = "Message-Only Window"
App.UI.Filter.DefaultGroup = "Process/Window"
App.UI.Filter.GroupTitle = "Group by"
App.UI.Filter.GroupByProcessTopLevelChild = "Process / Top-Level Window / Child Window"
App.UI.Filter.GroupByTopLevelChild = "Top-Level Window / Child Window"
App.UI.Filter.GroupByProcessWindow = "Process / Window"
App.UI.Filter.NoGroup = "None (Flatten Window List)"
App.UI.Filter.DefaultSearch = "Search"
App.UI.Filter.SearchTitle = "Search"
App.UI.Filter.SearchIncludingHwnd = "HWND (Exact Match)"
App.UI.Filter.SearchIncludingXid = "XID (Exact Match)"
App.UI.Filter.SearchIncludingTitle = "Window Title"
App.UI.Filter.SearchIncludingProcessName = "Process Name"
App.UI.Filter.DefaultSort = "Sort: None"
App.UI.Filter.SortTitle = "Sort"
App.UI.Filter.NoSort = "None"
App.UI.Filter.SortByHwnd = "Sort by HWND"
App.UI.Filter.SortByXid = "Sort by XID"
App.UI.Filter.SortByTitle = "Sort by Window Title"
App.UI.WindowDetail.EmptyWindowName = "Empty Title"
