Product.LocalizedName = "Window Debugger"
App.UI.SearchWatermark = "Search"
App.UI.SettingsButton = "Settings"
App.UI.AboutButton = "Settings"
App.UI.ReloadButton.Content = "Reload"
App.UI.ReloadButton.ToolTip.Title = "Reload"
App.UI.ReloadButton.ToolTip.Description = "Reload the window list."
App.UI.TopmostButton.Content = "Topmost"
App.UI.TopmostButton.ToolTip.Title = "Topmost"
App.UI.TopmostButton.ToolTip.Description = "Toggle the topmost state of the window."
App.UI.UacButton.Content = "UAC"
App.UI.UacButton.ToolTip.Title = "Restart as Administrator"
App.UI.UacButton.ToolTip.Description = "Restart this program with administrator privileges so that you can view and modify information of high privilege windows."
App.UI.Filter.DefaultFilter = "Visible Top-Level"
App.UI.Filter.FilterTitle = "Including these windows"
App.UI.Filter.FilterDescription = "By default, only visible top-level windows are shown in the list. Check to show more windows."
App.UI.Filter.IncludingInvisibleWindow = "Invisible Window"
App.UI.Filter.IncludingEmptyTitleWindow = "Empty Title Window"
App.UI.Filter.IncludingChildWindow = "Child Window"
App.UI.Filter.IncludingMessageOnlyWindow = "Message-Only Window"
App.UI.Filter.DefaultGroup = "Process/Window"
App.UI.Filter.GroupTitle = "Group by"
App.UI.Filter.GroupByProcessTopLevelChild = "Process / Top-Level Window / Child Window"
App.UI.Filter.GroupByTopLevelChild = "Top-Level Window / Child Window"
App.UI.Filter.GroupByProcessWindow = "Process / Window"
App.UI.Filter.NoGroup = "None (Flatten Window List)"
App.UI.Filter.DefaultSearch = "Search"
App.UI.Filter.SearchTitle = "Search"
App.UI.Filter.SearchIncludingHwnd = "HWND (Exact Match)"
App.UI.Filter.SearchIncludingXid = "XID (Exact Match)"
App.UI.Filter.SearchIncludingTitle = "Window Title"
App.UI.Filter.SearchIncludingProcessName = "Process Name"
App.UI.Filter.DefaultSort = "Sort: None"
App.UI.Filter.SortTitle = "Sort"
App.UI.Filter.NoSort = "None"
App.UI.Filter.SortByHwnd = "Sort by HWND"
App.UI.Filter.SortByXid = "Sort by XID"
App.UI.Filter.SortByTitle = "Sort by Window Title"
App.UI.WindowDetail.EmptyWindowName = "Empty Title"
App.UI.WindowDetail.ReloadButton.Content = "Reload Window Info"
App.UI.WindowDetail.ReloadButton.ToolTip.Title = "Reload Window Info"
App.UI.WindowDetail.ReloadButton.ToolTip.Description = "Reload all information of this window and display it on the interface."
App.UI.WindowDetail.OpenDirectory.Content = "Reveal in File Manager"
App.UI.WindowDetail.OpenDirectory.ToolTip.Title = "Reveal in File Manager"
App.UI.WindowDetail.OpenDirectory.ToolTip.Description = "View this program in the default file manager."
App.UI.WindowDetail.ChangeButton = "Change"
App.UI.WindowDetail.Pages.Windows.Info.Title = "Info"
App.UI.WindowDetail.Pages.Windows.Info.WindowHandle = "Handle"
App.UI.WindowDetail.Pages.Windows.Info.ProcessName = "Process Name"
App.UI.WindowDetail.Pages.Windows.Info.ProcessId = "Process Id"
App.UI.WindowDetail.Pages.Windows.Info.ThreadId = "Thread Id"
App.UI.WindowDetail.Pages.Windows.Info.ClassName = "Class Name"
App.UI.WindowDetail.Pages.Windows.Info.DpiAwareness = "DPI Awareness"
App.UI.WindowDetail.Pages.Windows.Info.Dpi = "DPI"
App.UI.WindowDetail.Pages.Windows.Info.WindowTitle = "Text"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Title = "Rect"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Description = "Screen coordinates"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Left = "Left"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Top = "Top"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Width = "Width"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Height = "Height"
App.UI.WindowDetail.Pages.Windows.Info.WindowShowStates = "Show States"
App.UI.WindowDetail.Pages.Windows.Info.WindowDisplayAffinity = "Display Affinity"
App.UI.WindowDetail.Pages.Windows.Info.ParentWindowHandle = "Parent Window"
App.UI.WindowDetail.Pages.Windows.Info.OwnerWindowHandle = "Owner Window"
App.UI.WindowDetail.Pages.Windows.Styles.Title = "Styles"
App.UI.WindowDetail.Pages.Windows.Styles.Subtitle = "Window Styles"
App.UI.WindowDetail.Pages.Windows.Styles.DocumentLink = "https://learn.microsoft.com/en-us/windows/win32/winmsg/window-styles"
App.UI.WindowDetail.Pages.Windows.StyleExes.Title = "StyleExes"
App.UI.WindowDetail.Pages.Windows.ClassStyles.Title = "ClassStyles"
App.UI.WindowDetail.Pages.Windows.Operations.Title = "Operations"
App.UI.WindowDetail.Pages.Windows.Dwm.Title = "DWM"
App.UI.WindowDetail.Pages.Windows.Others.Title = "Others"
App.UI.WindowDetail.Pages.Linux.Info.Title = "Info"
App.UI.WindowDetail.Pages.Linux.Properties.Title = "Properties"
App.UI.WindowDetail.Pages.Linux.Operations.Title = "Operations"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_INVALID = "Invalid DPI awareness"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_UNAWARE = "DPI unaware"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_SYSTEM_AWARE = "System DPI aware"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_PER_MONITOR_AWARE = "Per monitor DPI aware"
