Product.LocalizedName = "Window Debugger - 少珺窗口调试神器"
App.UI.SearchWatermark = "搜索"
App.UI.SettingsButton = "设置"
App.UI.AboutButton = "关于"
App.UI.ReloadButton.Content = "刷新"
App.UI.ReloadButton.ToolTip.Title = "刷新"
App.UI.ReloadButton.ToolTip.Description = "重新获取所有的窗口列表。"
App.UI.TopmostButton.Content = "置顶"
App.UI.TopmostButton.ToolTip.Title = "置顶"
App.UI.TopmostButton.ToolTip.Description = "将当前窗口置顶显示。"
App.UI.UacButton.Content = "管理员"
App.UI.UacButton.ToolTip.Title = "管理员权限"
App.UI.UacButton.ToolTip.Description = "以管理员权限重新启动此程序，以便可以查看和修改高权限窗口的信息。"
App.UI.Filter.DefaultFilter = "顶层可见"
App.UI.Filter.FilterTitle = "包含窗口"
App.UI.Filter.FilterDescription = "默认在列表中显示顶层可见窗口，勾选以显示更多窗口。"
App.UI.Filter.IncludingInvisibleWindow = "不可见窗口"
App.UI.Filter.IncludingEmptyTitleWindow = "无标题窗口"
App.UI.Filter.IncludingChildWindow = "子窗口"
App.UI.Filter.IncludingMessageOnlyWindow = "纯消息窗口"
App.UI.Filter.DefaultGroup = "进程/窗口"
App.UI.Filter.GroupTitle = "分组"
App.UI.Filter.GroupByProcessTopLevelChild = "进程 / 顶层窗口 / 子窗口"
App.UI.Filter.GroupByTopLevelChild = "顶层窗口 / 子窗口"
App.UI.Filter.GroupByProcessWindow = "进程 / 窗口"
App.UI.Filter.NoGroup = "无（以列表显示窗口）"
App.UI.Filter.DefaultSearch = "搜索"
App.UI.Filter.SearchTitle = "搜索"
App.UI.Filter.SearchIncludingHwnd = "句柄（需完全匹配）"
App.UI.Filter.SearchIncludingXid = "XID（需完全匹配）"
App.UI.Filter.SearchIncludingTitle = "标题"
App.UI.Filter.SearchIncludingProcessName = "进程名"
App.UI.Filter.DefaultSort = "排序：无"
App.UI.Filter.SortTitle = "排序"
App.UI.Filter.NoSort = "不排序"
App.UI.Filter.SortByHwnd = "按句柄排序"
App.UI.Filter.SortByXid = "按 XID 排序"
App.UI.Filter.SortByTitle = "按窗口标题排序"
App.UI.WindowDetail.EmptyWindowName = "无标题窗口"
App.UI.WindowDetail.ReloadButton.Content = "重新加载"
App.UI.WindowDetail.ReloadButton.ToolTip.Title = "重新加载"
App.UI.WindowDetail.ReloadButton.ToolTip.Description = "重新获取此窗口的所有信息，并显示在界面上。"
App.UI.WindowDetail.OpenDirectory.Content = "打开文件夹"
App.UI.WindowDetail.OpenDirectory.ToolTip.Title = "打开文件夹"
App.UI.WindowDetail.OpenDirectory.ToolTip.Description = "在默认的文件管理器中查看此程序。"
App.UI.WindowDetail.ChangeButton = "修改"
App.UI.WindowDetail.Pages.Windows.Info.Title = "信息"
App.UI.WindowDetail.Pages.Windows.Info.WindowHandle = "句柄"
App.UI.WindowDetail.Pages.Windows.Info.ProcessName = "进程名"
App.UI.WindowDetail.Pages.Windows.Info.ProcessId = "进程 ID"
App.UI.WindowDetail.Pages.Windows.Info.ThreadId = "线程 ID"
App.UI.WindowDetail.Pages.Windows.Info.ClassName = "窗口类\nClass Name"
App.UI.WindowDetail.Pages.Windows.Info.DpiAwareness = "DPI 感知级别"
App.UI.WindowDetail.Pages.Windows.Info.Dpi = "DPI"
App.UI.WindowDetail.Pages.Windows.Info.WindowTitle = "窗口标题"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Title = "位置和大小"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Description = "屏幕坐标系"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Left = "左"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Top = "上"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Width = "宽"
App.UI.WindowDetail.Pages.Windows.Info.Bounds.Height = "高"
App.UI.WindowDetail.Pages.Windows.Info.WindowShowStates = "显示状态\nShow States"
App.UI.WindowDetail.Pages.Windows.Info.WindowDisplayAffinity = "显示相关性\nDisplay Affinity"
App.UI.WindowDetail.Pages.Windows.Info.ParentWindowHandle = "父窗口\nParent"
App.UI.WindowDetail.Pages.Windows.Info.OwnerWindowHandle = "所有者窗口\nOwner"
App.UI.WindowDetail.Pages.Windows.Styles.Title = "样式 (STYLE)"
App.UI.WindowDetail.Pages.Windows.Styles.Subtitle = "窗口样式"
App.UI.WindowDetail.Pages.Windows.Styles.DocumentLink = "https://learn.microsoft.com/zh-cn/windows/win32/winmsg/window-styles"
App.UI.WindowDetail.Pages.Windows.StyleExes.Title = "扩展样式 (EXSTYLE)"
App.UI.WindowDetail.Pages.Windows.ClassStyles.Title = "类样式"
App.UI.WindowDetail.Pages.Windows.Operations.Title = "操作"
App.UI.WindowDetail.Pages.Windows.Dwm.Title = "DWM"
App.UI.WindowDetail.Pages.Windows.Others.Title = "其他"
App.UI.WindowDetail.Pages.Linux.Info.Title = "信息"
App.UI.WindowDetail.Pages.Linux.Properties.Title = "属性"
App.UI.WindowDetail.Pages.Linux.Operations.Title = "操作"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_INVALID = "无效"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_UNAWARE = "不知道"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_SYSTEM_AWARE = "系统感知"
Dynamic.EnumValues.DPI_AWARENESS.DPI_AWARENESS_PER_MONITOR_AWARE = "每个监视器感知"
