Product.LocalizedName = "Window Debugger - 少珺窗口调试神器"
App.UI.SearchWatermark = "搜索"
App.UI.SettingsButton = "设置"
App.UI.AboutButton = "关于"
App.UI.Filter.DefaultFilter = "顶层可见"
App.UI.Filter.FilterTitle = "包含窗口"
App.UI.Filter.FilterDescription = "默认在列表中显示顶层可见窗口，勾选以显示更多窗口。"
App.UI.Filter.IncludingInvisibleWindow = "不可见窗口"
App.UI.Filter.IncludingEmptyTitleWindow = "无标题窗口"
App.UI.Filter.IncludingChildWindow = "子窗口"
App.UI.Filter.IncludingMessageOnlyWindow = "纯消息窗口"
App.UI.Filter.DefaultGroup = "进程/窗口"
App.UI.Filter.GroupTitle = "分组"
App.UI.Filter.GroupByProcessTopLevelChild = "进程 / 顶层窗口 / 子窗口"
App.UI.Filter.GroupByTopLevelChild = "顶层窗口 / 子窗口"
App.UI.Filter.GroupByProcessWindow = "进程 / 窗口"
App.UI.Filter.NoGroup = "无（以列表显示窗口）"
App.UI.Filter.DefaultSearch = "搜索"
App.UI.Filter.SearchTitle = "搜索"
App.UI.Filter.SearchIncludingHwnd = "句柄（需完全匹配）"
App.UI.Filter.SearchIncludingXid = "XID（需完全匹配）"
App.UI.Filter.SearchIncludingTitle = "标题"
App.UI.Filter.SearchIncludingProcessName = "进程名"
App.UI.Filter.DefaultSort = "排序：无"
App.UI.Filter.SortTitle = "排序"
App.UI.Filter.NoSort = "不排序"
App.UI.Filter.SortByHwnd = "按句柄排序"
App.UI.Filter.SortByXid = "按 XID 排序"
App.UI.Filter.SortByTitle = "按窗口标题排序"
App.UI.WindowDetail.EmptyWindowName = "无标题窗口"
